### ISSUE TITLE
Follow up with Alicia to set up Ansible playbooks

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/cdh-ansible#212]
- [x] CDH Web
- [x] Geniza

**Comment by rlskoeser** [comment]
Successfully deployed cdhweb and geniza to staging using Ansible Tower; confirmed that the playbooks also still work when from a local dev enviroment.

These are the two most urgent playbooks to get running in Tower; dropping geotaste from the initial list since we haven't had any requests about that one.
